fix

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -49,23 +49,23 @@ jobs:
           key: ${{ runner.os }}-python-${{ matrix.python-version }}-${{ hashFiles('**.egg') }}
 
       - name: Install build tools
-          run: |
-            pip3 install flake8
-            #- pip3 install flake8-docstrings
-            pip3 install flake8-comprehensions
-            pip3 install pep8-naming
-          - name: Lint, format, and type-check
-            run: |
-              # stop the build if there are Python syntax errors or undefined names
-              flake8 --config=.flake8 .
-              black --check .
-              # Run type checker in CI such that type errors can be identified and gradually addressed.
-              # Once all existing type errors are addressed, the `|| echo` after the mypy call can be removed.
-              mypy syft || echo "Type errors found, continuing build..."
-          - name: Check docstring coverage
-            run: |
-              interrogate -mvp syft/ -f 52.5
-          - name: Scan for security issues
-            run: |
-              pip install bandit
-              bandit -r syft -ll
+        run: |
+          pip3 install flake8
+          #- pip3 install flake8-docstrings
+          pip3 install flake8-comprehensions
+          pip3 install pep8-naming
+      - name: Lint, format, and type-check
+        run: |
+          # stop the build if there are Python syntax errors or undefined names
+          flake8 --config=.flake8 .
+          black --check .
+          # Run type checker in CI such that type errors can be identified and gradually addressed.
+          # Once all existing type errors are addressed, the `|| echo` after the mypy call can be removed.
+          mypy syft || echo "Type errors found, continuing build..."
+      - name: Check docstring coverage
+        run: |
+          interrogate -mvp syft/ -f 52.5
+      - name: Scan for security issues
+        run: |
+          pip install bandit
+          bandit -r syft -ll
