Add line to install mypy
See [this](https://mypy.readthedocs.io/en/stable/getting_started.html) for more info.

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -56,12 +56,15 @@ jobs:
           pip3 install pep8-naming
           pip3 install interrogate
           pip3 install black
+          python3 -m pip install mypy
       - name: Lint, format, and type-check
         run: |
           # stop the build if there are Python syntax errors or undefined names
           flake8 --config=.flake8 .
           black --check .
           # Run type checker in CI such that type errors can be identified and gradually addressed.
+          # Once all existing type errors are addressed, the `|| echo` after the mypy call can be removed.
+          mypy src || echo "Type errors found, continuing build..."
       - name: Check docstring coverage
         run: |
           interrogate -mvp src/ -f 52.5
